from dotenv import load_dotenv
from elasticsearch import Elasticsearch
import os

load_dotenv()

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = os.getenv("ELASTIC_PASSWORD")

# Found in the 'Manage Deployment' page
CLOUD_ID = os.getenv("ELASTIC_CLOUD_ID")
# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
client.info()
# {'name': 'instance-0000000000', 'cluster_name': ...}